"""Domain enums for MAYA product entities."""

from __future__ import annotations

import enum


class UserRole(str, enum.Enum):
    INVESTIGATOR = "INVESTIGATOR"
    ADMIN = "ADMIN"


class CaseStatus(str, enum.Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class CasePriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class EvidenceStatus(str, enum.Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    ANALYZED = "ANALYZED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class AnalysisStatus(str, enum.Enum):
    NONE = "NONE"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class FaceVerificationStatus(str, enum.Enum):
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class FaceVerificationDecision(str, enum.Enum):
    MATCH = "MATCH"
    NO_MATCH = "NO_MATCH"
    INCONCLUSIVE = "INCONCLUSIVE"


class IntegrityStatus(str, enum.Enum):
    VALID = "VALID"
    TAMPERED = "TAMPERED"
    MODIFIED = "MODIFIED"
    MISSING = "MISSING"
    ERROR = "ERROR"


class AuditEventType(str, enum.Enum):
    USER_REGISTERED = "USER_REGISTERED"
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    CASE_CREATED = "CASE_CREATED"
    CASE_UPDATED = "CASE_UPDATED"
    CASE_CLOSED = "CASE_CLOSED"
    CASE_DELETED = "CASE_DELETED"
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    EVIDENCE_ACCESSED = "EVIDENCE_ACCESSED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"
    XAI_GENERATED = "XAI_GENERATED"
    XAI_FAILED = "XAI_FAILED"
    REPORT_GENERATED = "REPORT_GENERATED"
    FACE_VERIFICATION_STARTED = "FACE_VERIFICATION_STARTED"
    FACE_VERIFICATION_COMPLETED = "FACE_VERIFICATION_COMPLETED"
    FACE_VERIFICATION_FAILED = "FACE_VERIFICATION_FAILED"
